dist: xenial

services:
- docker

env:
  global:
  - REPO=dhlabbasel/ark-resolver
  - secure: SPWW7/NoiFp8HDsp/0ncURaFMzshyi8AlD5GfiarppGAKPZDmQSarv+00b5vkCsHeZB6m4y/GsnzseeQ8w15U/gSqgle0hOIp5cJrnTuo33FlkueTO6Blp1z23lpScOPUu3xts28V0M18Bap/DEjXWKqpLn1QLT4nv4S+tCegU4iHKv+YAPZAMPh95AfI3HxpsrO818mMEdscmnXfM22UFXTBsC+/9fRxT9VRjWcblyLHfbeILmNXebOJBPt813kFSql/GRe4WMs9hKSszZGqiXTTgBrUhjKYyzRH5XaUQ2QwrM+p7ufdcXM171JoGW4eXHQIDPl1GO6YHFKoRN+5+ld1Q0D8Rbczvn0hF1TwIJjC6lEk/Tv0Nvt0OZH06WClWVQ6wRyJt2UIqKH93uY+GKdFRdGGoHrDjiw1hTxoRZpRM/Haw+Nx2REvGUnl1YainKWbHYvOmjuOXE8JrtM1nf/kSzAv5ZPymVUyK8rf/Ke+HXKO31wO/PVcGeVtdgeFgTdDzwsDipxB7eSPcQ12ZRfs+RV1IEl2qHZEFMe1nWirtT/KxiJ6n12R4i+dj6REYFo5zlqFL/YXq+nMAcGsr0NL9MbouwD1tjlCce9bcchqJMJ4jaNrq8f7Vh4ZCVrPVN+LJaBwhZjbC+HWP9eQZsPh29DX+cshHrhmgie4ek=
  - secure: i3SdBQrG7vMRnjQ7Z8nIDcpn8HhCoLv5hD5xRzTjroL/IWN6gOqh2cFXY6DXKhcCZIqSF2vsor1RjyC8unMbuAixuUV1jo+IN7pYPoEnvkLUfzpU//z4xCfVObY8Uh7GIJv88cr1t7o6ZfTeAsnnljICPof4vj2SHmTAuQb+3uSF/zYMNkhB00ZOlyaevgFjjdGSZZbtrNpxpM7fFpMfDd7vym25Qvf8olGCsGRlPcgQZgkxUuxpShWmsOrqxz62xUzOJEdhj7GMI6xSSctSYjjLAkcxQC00P9Wnu3Xw2MhGh34RU2EgwmqdOyLAt5w7vbp65SY4x1dQxsrCyzFSVmT9bfYJA7Byj4YnylGAs87PpoX2vbiC8AxQuL0nW4lj8rwzT301BtDAuzvfU/V7anS+FJU560C+kxpFBVAEGhllWYFqSIng3PM4xco/1cg6nnDJZ4QgfAPxn/Ts9Ke/8N+CpoPHCZxV5kdJzxZTENtmghBI3pO0zrGzRGVzlSnaXjHJwXHKoB048Y2HYS/ic0s7E80G9FRtUDm0zp0DmrNVII1JtdyhSaDVi4zjtbP1yamowazWmwz82ctWkBL5q5C2kf6xlUxpYYZjuRSW0hsRjT8M/6vTQKxymSxufCs5Sg/RJ0ZO5CVTSHe1477qL6WQArUckJZTd5Kw9D97JJs=

stages:
- test
- name: publish
  if: branch = master OR tag IS present

jobs:
  include:
  - stage: test
    script:
    - docker build -t $REPO .
    - docker run $REPO --test
  - stage: publish
    script:
    - TAG=$(git describe --tags)
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    - docker build -t $REPO:$TAG .
    - docker tag $REPO:$TAG $REPO:latest
    - docker push $REPO
notifications:
  slack:
    secure: PxvA5zguh3T64J+c7JHnXtKM9jo8S5qIDJ6IT7d2l66xI48Hf3hiM/Tr9C+Duc1krrMViB935AzDFaK5QZPOgzbzHd1AMugLTSD/ds+puimZ8W8gwZVH3MkYyqPXVofCEZaCKPbGOQTQ5Z6wAaGLZ2wuaAwMaqvKi8fMPc6r7M/Ggaagsiw8t9ScRcMTFt2PbmXfdcazIaPigMramLFXDel+AgFW3ay5D9ophs2QsfRlNAxd1OxAHZFIgoimI13H9fM7Efs1TWBywqUVkd9Fsl5aiY5zEcJN7NezgAJrUynL9FJwPBV+NcOAfm/WBqJ82K0zCSE2blhLr2ixVsfhuceEUXVa/2Y1qthOkKFEgggcfnth7D12RjLOY5Qr8J8f9q45A1cTqsiitKS9qfgulcV1fNqho4X9EROrVY20Li9eWNDQOK4EiHclpfnBZ1NVH0DrRt7y19zdyW749RUOy9NO1MMhjl93E6K9KELVGlfCOsm9ZxKGzZsV4XA3nClXlIn7IdE7jlc/bmyC0nWf8HGge8l+HSJp0c4F078VOF5eIq3aNm9H740736ycSr/W6Puj34QblFTslR4/7qCDtfB/Hf7HNyPSK+thiHlNUZa4WeOT7lb/iDHevpCBQ2+HFQFfxwLIFbC+jlZKQfRNHIwoHG5rzCZPf1stUtREKN0=
