# get us a vm with ubuntu 16.04
dist: xenial

# provides us docker
services:
  - docker

# define some additional environment variables
env:
  global:
    - REPO=dhlabbasel/ark-resolver

stages:
  - test
  - name: publish # generally, only publish if we are on 'master' or tagged
    if: branch = master OR tag IS present

jobs:
  include:
    - stage: test
      script:
        - docker build -t $REPO .
        - docker run $REPO --test

    - stage: publish
      script:
        - TAG=$(git describe --tags)
        - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
        - docker build -t $REPO:$TAG .
        - docker tag $REPO:$TAG $REPO:latest
        - docker push $REPO

notifications:
  slack:
    secure: "PxvA5zguh3T64J+c7JHnXtKM9jo8S5qIDJ6IT7d2l66xI48Hf3hiM/Tr9C+Duc1krrMViB935AzDFaK5QZPOgzbzHd1AMugLTSD/ds+puimZ8W8gwZVH3MkYyqPXVofCEZaCKPbGOQTQ5Z6wAaGLZ2wuaAwMaqvKi8fMPc6r7M/Ggaagsiw8t9ScRcMTFt2PbmXfdcazIaPigMramLFXDel+AgFW3ay5D9ophs2QsfRlNAxd1OxAHZFIgoimI13H9fM7Efs1TWBywqUVkd9Fsl5aiY5zEcJN7NezgAJrUynL9FJwPBV+NcOAfm/WBqJ82K0zCSE2blhLr2ixVsfhuceEUXVa/2Y1qthOkKFEgggcfnth7D12RjLOY5Qr8J8f9q45A1cTqsiitKS9qfgulcV1fNqho4X9EROrVY20Li9eWNDQOK4EiHclpfnBZ1NVH0DrRt7y19zdyW749RUOy9NO1MMhjl93E6K9KELVGlfCOsm9ZxKGzZsV4XA3nClXlIn7IdE7jlc/bmyC0nWf8HGge8l+HSJp0c4F078VOF5eIq3aNm9H740736ycSr/W6Puj34QblFTslR4/7qCDtfB/Hf7HNyPSK+thiHlNUZa4WeOT7lb/iDHevpCBQ2+HFQFfxwLIFbC+jlZKQfRNHIwoHG5rzCZPf1stUtREKN0="
