---

name: PR Title

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[a-z]+!?: .+$|^chore: release \d+\.\d+\.\d+$'
          allowed_prefixes: "fix,refactor,feat,docs,chore,style,test" 
          disallowed_prefixes: "feature,hotfix" 
          prefix_case_sensitive: true 
          max_length: 140
