---

name: Publish to Docker Hub foo

on:
  release:
    types: [published]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-to-dockerhub:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Disk Free
        run: |
          df -h
          docker system df
          docker system prune --all --force --volumes
          df -h
      - name: build and publish all images to Dockerhub
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          make publish
      - name: Disk Free After
        run: |
          df -h
          docker system df
